= Changelog

:sectnums!:

== link:++https://github.com/saltstack-formulas/jetbrains-appcode-formula/compare/v1.0.2...v1.0.3++[1.0.3^] (2020-12-16)

=== Continuous Integration

* *gitlab-ci:* use GitLab CI as Travis CI replacement
(https://github.com/saltstack-formulas/jetbrains-appcode-formula/commit/49a028af0800c2f1c00968f933132bf01ba341ea[49a028a^])
* *pre-commit:* add to formula [skip ci]
(https://github.com/saltstack-formulas/jetbrains-appcode-formula/commit/190e3f74f1ce3084b4cee89ce88a5257fcdcae12[190e3f7^])
* *pre-commit:* enable/disable `rstcheck` as relevant [skip ci]
(https://github.com/saltstack-formulas/jetbrains-appcode-formula/commit/d9760ef5066cdfe69d83c2317dbacca0e3596663[d9760ef^])
* *pre-commit:* finalise `rstcheck` configuration [skip ci]
(https://github.com/saltstack-formulas/jetbrains-appcode-formula/commit/336a70243a25887c4c090ca69c21447dbd365cb6[336a702^])

=== Documentation

* *readme:* fix `rstcheck` violation [skip ci]
(https://github.com/saltstack-formulas/jetbrains-appcode-formula/commit/83d8993d9d02aa6a527d8bac9c9ab0032e71ae81[83d8993^]),
closes
https://github.com//travis-ci.org/github/myii/jetbrains-appcode-formula/builds/731606929/issues/L259[/travis-ci.org/github/myii/jetbrains-appcode-formula/builds/731606929#L259^]

== link:++https://github.com/saltstack-formulas/jetbrains-appcode-formula/compare/v1.0.1...v1.0.2++[1.0.2^] (2020-07-28)

=== Bug Fixes

* *cmd.run:* wrap url in quotes (zsh)
(https://github.com/saltstack-formulas/jetbrains-appcode-formula/commit/86c256b657f12bf882dd9b20886ac8bd9377ede9[86c256b^])
* *macos:* correct syntax
(https://github.com/saltstack-formulas/jetbrains-appcode-formula/commit/36292b448e1dfd17f0eed6f24e4d9c768ed3d1ab[36292b4^])

=== Code Refactoring

* *jetbrains:* align all jetbrains formulas
(https://github.com/saltstack-formulas/jetbrains-appcode-formula/commit/ffc4b9727264b5ba3c5ca804db5fb6b661797a1f[ffc4b97^])
* *macos:* handle /applications
(https://github.com/saltstack-formulas/jetbrains-appcode-formula/commit/d153a67a6750d5f3e02f70f75a4562f7b5317dde[d153a67^])
* *path:* consistent path vars
(https://github.com/saltstack-formulas/jetbrains-appcode-formula/commit/2338c2d0ea345f984786edb48496c7c4502d52fc[2338c2d^])

=== Continuous Integration

* *kitchen:* use `saltimages` Docker Hub where available [skip ci]
(https://github.com/saltstack-formulas/jetbrains-appcode-formula/commit/c44d0433363c1cbc8d861ebc903189798c55e10d[c44d043^])

=== Documentation

* *readme:* minor update
(https://github.com/saltstack-formulas/jetbrains-appcode-formula/commit/73b1d8b1d9285776689ef776d064c0d3277d6bda[73b1d8b^])

=== Styles

* *libtofs.jinja:* use Black-inspired Jinja formatting [skip ci]
(https://github.com/saltstack-formulas/jetbrains-appcode-formula/commit/b8e7867ac18b73e0f9549ff215e46963143def3e[b8e7867^])

== link:++https://github.com/saltstack-formulas/jetbrains-appcode-formula/compare/v1.0.0...v1.0.1++[1.0.1^] (2020-06-15)

=== Bug Fixes

* *edition:* better edition jinja code
(https://github.com/saltstack-formulas/jetbrains-appcode-formula/commit/ad2f79795633da937d8e2feb9cd20ae840c507e8[ad2f797^])

=== Continuous Integration

* *kitchen+travis:* add new platforms [skip ci]
(https://github.com/saltstack-formulas/jetbrains-appcode-formula/commit/ddf769be52a84b94fb49afb7a526d72d4bfeeb0f[ddf769b^])

=== Documentation

* *readme:* update formattings
(https://github.com/saltstack-formulas/jetbrains-appcode-formula/commit/2969be7ee177606ac7cd3a7fe7f8d4d93c0d1ef9[2969be7^])

== link:++https://github.com/saltstack-formulas/jetbrains-appcode-formula/compare/v0.1.0...v1.0.0++[1.0.0^] (2020-05-22)

=== Bug Fixes

* *id:* rename conflicting id
(https://github.com/saltstack-formulas/jetbrains-appcode-formula/commit/f4055fffa98d03176c90b7164ba05b7697d632aa[f4055ff^])
* *state:* remove duplicate include
(https://github.com/saltstack-formulas/jetbrains-appcode-formula/commit/270a60fcf436033d5eba784ed44d3ab822bb7000[270a60f^])
* *state:* remove duplicate include
(https://github.com/saltstack-formulas/jetbrains-appcode-formula/commit/24cecdadfa656546d7d78725d6335b4bcf3bbf03[24cecda^])

=== Continuous Integration

* *kitchen+travis:* adjust matrix to add `3000.3`
(https://github.com/saltstack-formulas/jetbrains-appcode-formula/commit/d2c5950345e9fc7179ecb5c91d0cb6dfeb5f097a[d2c5950^])
* *travis:* update travis tests
(https://github.com/saltstack-formulas/jetbrains-appcode-formula/commit/31094d7865b52e2d32dddb51b90ba279bce4c5b9[31094d7^])

=== Documentation

* *readme:* add depth one
(https://github.com/saltstack-formulas/jetbrains-appcode-formula/commit/a0f9a4c77e4a8e2ec3dcb2182d6402c5f0116bd6[a0f9a4c^])

=== Features

* *formula:* align to template-formula; add ci
(https://github.com/saltstack-formulas/jetbrains-appcode-formula/commit/bc70a976381b909ebaef96cc60047fbc44510859[bc70a97^])
* *formula:* align to template-formula; add ci
(https://github.com/saltstack-formulas/jetbrains-appcode-formula/commit/dd34d6eed766029e415700cd5a852549a0896ec0[dd34d6e^])
* *semantic-release:* standardise for this formula
(https://github.com/saltstack-formulas/jetbrains-appcode-formula/commit/feb078410ec61657b23b62be31f0bbd1e0f885a1[feb0784^])

=== BREAKING CHANGES

* *formula:* Major refactor of formula to bring it in alignment with the
template-formula. As with all substantial changes, please ensure your
existing configurations work in the ways you expect from this formula.
